version: '2'

services:
  haproxy:
    image: haproxy:alpine
    container_name: haproxy
    restart: always
    depends_on:
      - dockergen
    ports:
      - "80:80"
    volumes:
      - haproxy_conf:/usr/local/etc/haproxy
    networks:
      - default
      - proxy

  dockergen:
    image: jwilder/docker-gen
    container_name: haproxy_generator
    command: -notify-sighup haproxy -watch /etc/docker-gen/templates/haproxy.tmpl /usr/local/etc/haproxy/haproxy.cfg
    restart: always
    volumes:
      - haproxy_conf:/usr/local/etc/haproxy
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./haproxy.tmpl:/etc/docker-gen/templates/haproxy.tmpl

volumes:
  haproxy_conf:

networks:
  proxy:
    external: true
